BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Button:
            size_hint_x: 0.1
            text: 'one'
        Button:
            size_hint_x: 0.8
            text: 'two'
        Button:
            size_hint_x: 0.1
            text: 'three'
    BoxLayout:
        orientation: 'vertical'
        Label:
            size_hint_y: 0.2
            text: 'Hello'
        Button:
            size_hint_y: 0.8
            text: 'four'


